# Generated by Django 6.0.2 on 2026-02-18 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("gold", "Gold"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=10,
                    ),
                ),
                ("schema_name", models.CharField(max_length=100)),
                (
                    "database_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_migrating", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "tenants",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="tenants.user",
                    ),
                ),
            ],
            options={
                "db_table": "blogs",
            },
        ),
    ]
