# Generated by Django 6.0.2 on 2026-02-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="Blogs",
        ),
    ]
