# Generated by Django 6.0.2 on 2026-02-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE users ENABLE ROW LEVEL SECURITY;

                CREATE POLICY tenant_isolation_policy
                ON users
                USING (
                    tenant_id = current_setting('app.current_tenant')::uuid
                )
                WITH CHECK (
                    tenant_id = current_setting('app.current_tenant')::uuid
                );
            """,
            reverse_sql="""
                DROP POLICY IF EXISTS tenant_isolation_policy ON users;
                ALTER TABLE users DISABLE ROW LEVEL SECURITY;
            """
        )
    ]
