# Generated by Django 6.0.2 on 2026-02-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_rls_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="schema_name",
            field=models.CharField(max_length=100),
        ),
    ]
