# Generated by Django 6.0.2 on 2026-02-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_tenant_schema_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="db_name",
            field=models.CharField(default="default", max_length=100),
        ),
    ]
