# Generated by Django 6.0.2 on 2026-02-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="sub_domain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
