# Generated by Django 6.0.2 on 2026-02-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenant_db_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("gold", "Gold"),
                    ("enterprise", "Enterprise"),
                ],
                max_length=10,
            ),
        ),
    ]
