# Generated by Django 6.0.2 on 2026-02-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_alter_tenant_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="db_name",
        ),
    ]
