# Generated by Django 6.0.2 on 2026-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_remove_tenant_db_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="database_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
